apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: standard
spec:
  replicas: 1  # Nombre exact de réplicas spécifié
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql-container
          image: postgres:12.0-alpine
          envFrom:
            - secretRef:
                name: postgresql-credentials
            - configMapRef:
                name: postgresql-config
