apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - clusterissuer.yaml
  - horizontalpodautoscaler.yaml
  - ingress.yaml
  - postgres-configmap.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - pgadmin-configmap.yaml
  - pgadmin-secret.yaml
  - pgadmin-deployment.yaml
  - pgadmin-service.yaml

