apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "fastapi.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
