apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-fastapi-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
