apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-fastapi-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DATABASE_USER: YWRtaW4= # base64 encoded 'admin'
  DATABASE_PASSWORD: cGFzc3dvcmQ= # base64 encoded 'password'
