apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-pgadmin-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort
