apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-postgresql
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ include "my-helm-chart.fullname" . }}-postgresql
  replicas: {{ .Values.postgresql.replicas }}
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:12.0-alpine
          envFrom:
            - secretRef:
                name: {{ include "my-helm-chart.fullname" . }}-postgresql-credentials
            - configMapRef:
                name: {{ include "my-helm-chart.fullname" . }}-postgresql-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-pvc
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgresql-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgresql.storage.size }}
