apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-postgresql-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_DB: "storedb"
  POSTGRES_HOST_AUTH_METHOD: "trust"

