apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-postgresql-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
