apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fastapi-hpa
  namespace: standard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi-deployment  # Remplacez par le nom de votre déploiement
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
