apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-credentials
  namespace: standard
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t  # base64 encoded 'admin@admin.com'
  PGADMIN_DEFAULT_PASSWORD: cm9vdA==  # base64 encoded 'root'
